CFLAGS=-Wall -Wextra -Wdouble-promotion -Wconversion -Wsign-conversion

all: programa1 programa2 programa3

$programa1 : programa1.c
	gcc $(CFLAGS) -o $@ $^

$programa2 : programa2.c
	gcc $(CFLAGS) -o $@ $^

$programa3: programa3.c
	gcc $(CFLAGS) -o $@ $^

